---
#!/usr/bin/env ansible-playbook

- name: Setup Home Environment on Mac
  hosts: 127.0.0.1
  connection: local
  become: true
  tasks:

  - name: Updating and upgrading apt packages
    apt:
      upgrade: yes

  - name: Preinstallation process
    package:
      name:
      - ca-certificates
      - curl
      - nginx
      - docker-compose

  - name: vim theme jelly beans

  - name: .vimrc

  - name: .bashrc

  - name: golangci-lint

  - name: go 1.18

  - name: pre-commit

  - name: python

  - name: VScode (?config?)

  - name: Adding Docker GPG-key
    apt_key:
      url: https://download.docker.com/linux/ubuntu/gpg
      state: present

  - name: Adding Docker Repo
    apt_repository:
      repo: deb https://download.docker.com/linux/ubuntu bionic stable
      state: present

  - name: Updating apt and installing docker
    package:
      name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      state: latest

  - name: Starting NGINX
    systemd:
      name: nginx
      enabled: yes
      state: started
      daemon_reload: yes

